"use client";
import { Button, Group, Stack } from "@mantine/core";
import { ArrowClockwise, Sparkle } from "@phosphor-icons/react";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState, useSyncExternalStore } from "react";
import { useLocale } from "@/components/locale-provider";
import {
  analysisRunKey,
  getAnalysisRunState,
  getServerAnalysisRunState,
  registerAnalysisRefresh,
  startAnalysisRun,
  subscribeToAnalysisRuns,
} from "@/lib/analysis-runs";
import type { AnalysisArtifact, AnalysisLens, AnalysisPage } from "@/lib/types";
import { Freshness, Notice, Panel, Pending, useCopy } from "./foundation";

type NarrativeProps = {
  lens: AnalysisLens;
  page: AnalysisPage;
  ticker?: string;
  snapshot?: string;
};

// Keep analysis panels unmounted while the AI experience is being redesigned.
const SHOW_AI_ANALYSIS = false;

export function Narrative(props: NarrativeProps) {
  return SHOW_AI_ANALYSIS ? <NarrativePanel {...props} /> : null;
}

function NarrativePanel({ lens, ticker, snapshot }: NarrativeProps) {
  const t = useCopy();
  const { locale } = useLocale();
  const [opened, setOpened] = useState(false);
  const key = analysisRunKey(lens, ticker);
  const run = useSyncExternalStore(
    subscribeToAnalysisRuns,
    () => getAnalysisRunState(key),
    getServerAnalysisRunState,
  );
  const active = run.status === "queued" || run.status === "running";
  const query = useQuery({
    queryKey: ["workspace-narrative", snapshot, lens, ticker],
    enabled: opened,
    retry: 0,
    queryFn: async () => {
      const response = await fetch(
        "/api/backend/analysis?lens=" +
          lens +
          (ticker ? "&ticker=" + encodeURIComponent(ticker) : "") +
          (snapshot ? "&snapshot_run_id=" + encodeURIComponent(snapshot) : ""),
      );
      if (response.status === 404) return null;
      if (!response.ok) throw new Error("Analysis unavailable");
      return response.json() as Promise<AnalysisArtifact>;
    },
  });
  const refetch = query.refetch;
  useEffect(
    () =>
      registerAnalysisRefresh(() => {
        void refetch();
      }),
    [refetch],
  );
  return (
    <Panel
      title={
        <Group gap={8}>
          <Sparkle size={18} />
          {t("把数据串成观点", "Connect the evidence")}
        </Group>
      }
      description={t(
        "AI 生成",
        "AI generated",
      )}
      action={
        <Button variant="subtle" onClick={() => setOpened(!opened)}>
          {opened ? t("收起", "Collapse") : t("展开分析", "Read analysis")}
        </Button>
      }
    >
      {opened && (
        <Stack gap="md">
          {query.isPending ? (
            <Pending compact />
          ) : query.data ? (
            <>
              <div className="mx-prose">
                <h3>{query.data.content.headline[locale]}</h3>
                <p>{query.data.content.summary[locale]}</p>
                {query.data.content.evidence.map((e, i) => (
                  <p key={i}>
                    <strong>{e.label[locale]}</strong> · {e.detail[locale]}
                  </p>
                ))}
                <h3>
                  {t("需要保持怀疑的地方", "What could challenge this view")}
                </h3>
                <ul>
                  {[
                    ...query.data.content.counterpoints,
                    ...query.data.content.risks,
                  ].map((e, i) => (
                    <li key={i}>{e[locale]}</li>
                  ))}
                </ul>
                <h3>
                  {t("什么会使观点失效", "What would invalidate this view")}
                </h3>
                <ul>
                  {query.data.content.invalidationConditions.map((e, i) => (
                    <li key={i}>{e[locale]}</li>
                  ))}
                </ul>
                <h3>{t("下一步观察", "What to watch next")}</h3>
                <ul>
                  {query.data.content.nextObservations.map((e, i) => (
                    <li key={i}>{e[locale]}</li>
                  ))}
                </ul>
              </div>
              <Freshness date={query.data.generatedAt} />
              {query.data.fake && (
                <Notice>
                  {t(
                    "这是测试提供商生成的示例内容。",
                    "This content was generated by a test provider.",
                  )}
                </Notice>
              )}
            </>
          ) : (
            <Notice>
              {query.isError
                ? t(
                    "暂时无法读取分析。可以重试，或检查模型连接。",
                    "Analysis could not be loaded. Retry or check your model connection.",
                  )
                : t(
                    "还没有这份分析。配置模型提供商后，可按需生成。",
                    "No analysis yet. Connect a model provider to generate one when needed.",
                  )}
            </Notice>
          )}
          {run.status === "failed" && (
            <Notice tone="bad">
              {t(
                "生成未完成，请检查模型连接后重试。",
                "Generation did not complete. Check your model connection and retry.",
              )}
            </Notice>
          )}
          <Button
            variant="default"
            loading={active}
            leftSection={<ArrowClockwise size={15} />}
            onClick={() => void startAnalysisRun({ lens, ticker })}
          >
            {active
              ? t("正在分析", "Analyzing")
              : t("生成最新分析", "Generate analysis")}
          </Button>
        </Stack>
      )}
    </Panel>
  );
}
